### ISSUE TITLE
注释所指是"Bearer "前缀，而各个application.yml中配置的是"Bearer"

### ISSUE THREAD

**Issue by pppobear** [macrozheng/mall#303]
https://github.com/macrozheng/mall/blob/7fba1a99f437284b0592b72ba1934a91a7b4e46e/mall-security/src/main/java/com/macro/mall/security/component/JwtAuthenticationTokenFilter.java#L42

这里的注释有个小问题，因为我看各个application.yml配置的jwt.tokenHead都是
```yaml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
```
读出来会变成 "Bearer", 而导致Token前面有个空格

![image](https://user-images.githubusercontent.com/21952175/76147394-cc97f500-60d6-11ea-99af-42c14f942903.png)

应该配置成
```yaml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: 'Bearer ' #JWT负载中拿到开头
```
